# Generated by Django 3.2.4 on 2021-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humaniser2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_month',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(default=None),
        ),
    ]
