# Generated by Django 3.2.4 on 2021-06-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humaniser2', '0003_auto_20210626_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birth_date',
            new_name='birth_day',
        ),
    ]
